function = "bin.critical.main"
n_seeds = 5

[base_config]
n_steps = 3000
patience = 1000
save_checkpoint = false
amp_dtype = "bfloat16"

[base_config.optimizer]
type = "AdamW"
lr = 0.0011767631029856202
weight_decay = 0.0003995196569743507

[base_config.data]
path = "data/city-roads-M"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
seed = 0
labels = true

[base_config.transform.features]
num_policy = "quantile-normal"
cat_policy = "one-hot"
impute_first = true

[base_config.model.backbone]
conv = "gt"
n_blocks = 9
d_hidden = 384
dropout = 0.15000000000000002
log2_hidden_dim_multiplier = 2
normalization = "Identity"
log2_n_heads = 2
sep = false
