function = "bin.cgasb.main"
n_seeds = 5

[base_config]
n_steps = 3000
patience = 1000
save_checkpoint = false

[base_config.optimizer]
type = "AdamW"
lr = 8.130591086319805e-05
weight_decay = 0.01213798020283666

[base_config.data]
path = "data/hm-prices"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
seed = 0
labels = true

[base_config.transform.features]
num_policy = "quantile-normal"
cat_policy = "one-hot"
impute_first = true

[base_config.model.backbone]
conv = "gat"
n_blocks = 1
d_hidden = 224
dropout = 0.0
pre_linear = false
res = true
norm = "none"
log2_n_heads = 2
