function = "bin.cgasb.main"
n_seeds = 5

[base_config]
n_steps = 3000
patience = 1000
save_checkpoint = false
amp_dtype = "bfloat16"

[base_config.optimizer]
type = "AdamW"
lr = 9.145961007482022e-05
weight_decay = 0.26893590530037353

[base_config.data]
path = "data/artnet-exp"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
seed = 0
labels = false

[base_config.transform.features]
num_policy = "quantile-normal"
cat_policy = "one-hot"
impute_first = true

[base_config.model.backbone]
conv = "gcn"
n_blocks = 3
d_hidden = 256
dropout = 0.5
pre_linear = true
res = true
norm = "bn"
