function = "bin.critical.main"
n_seeds = 5

[base_config]
n_steps = 3000
patience = 1000
save_checkpoint = false
amp_dtype = "bfloat16"

[base_config.optimizer]
type = "AdamW"
lr = 0.0004949713652134788
weight_decay = 0.00023728668723209514

[base_config.data]
path = "data/city-roads-L"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
seed = 0
labels = true

[base_config.transform.features]
num_policy = "quantile-normal"
cat_policy = "one-hot"
impute_first = true

[base_config.model.backbone]
conv = "sage"
n_blocks = 6
d_hidden = 416
dropout = 0.1
log2_hidden_dim_multiplier = 2
normalization = "BatchNorm"
