function = "bin.critical.main"
n_seeds = 5

[base_config]
n_steps = 3000
patience = 1000
save_checkpoint = false

[base_config.optimizer]
type = "AdamW"
lr = 0.0005142807198946635
weight_decay = 0.004518796386141417

[base_config.data]
path = "data/hm-categories"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
seed = 0
labels = false

[base_config.transform.features]
num_policy = "quantile-normal"
cat_policy = "one-hot"
impute_first = true

[base_config.model.backbone]
conv = "gat"
n_blocks = 8
d_hidden = 128
dropout = 0.2
log2_hidden_dim_multiplier = 2
normalization = "LayerNorm"
log2_n_heads = 3
sep = false
