function = "bin.critical.main"
n_seeds = 5

[base_config]
n_steps = 3000
patience = 1000
save_checkpoint = false

[base_config.optimizer]
type = "AdamW"
lr = 0.00022836151962650519
weight_decay = 0.007399519988706526

[base_config.data]
path = "data/avazu-ctr"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
seed = 0
labels = true

[base_config.transform.features]
frac_policy = "quantile-normal"
impute_first = true

[base_config.model.backbone]
conv = "gt"
n_blocks = 9
d_hidden = 576
dropout = 0.2
log2_hidden_dim_multiplier = 1
normalization = "Identity"
log2_n_heads = 1
sep = true
