function = "bin.cgasb.main"
n_seeds = 5

[base_config]
n_steps = 3000
patience = 1000
save_checkpoint = false

[base_config.optimizer]
type = "AdamW"
lr = 0.006988332452374559
weight_decay = 0.23495612893090728

[base_config.data]
path = "data/avazu-ctr"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
seed = 0
labels = true

[base_config.transform.features]
frac_policy = "quantile-normal"
impute_first = true

[base_config.model.backbone]
conv = "sage"
n_blocks = 2
d_hidden = 352
dropout = 0.15000000000000002
pre_linear = true
res = false
norm = "bn"
