function = "bin.critical.main"
n_seeds = 5

[base_config]
n_steps = 3000
patience = 1000
save_checkpoint = false

[base_config.optimizer]
type = "AdamW"
lr = 0.00024771655827351914
weight_decay = 0.07701139662463294

[base_config.data]
path = "data/hm-prices"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
seed = 0
labels = true

[base_config.transform.features]
num_policy = "quantile-normal"
cat_policy = "one-hot"
impute_first = true

[base_config.model.backbone]
conv = "sage"
n_blocks = 10
d_hidden = 192
dropout = 0.05
log2_hidden_dim_multiplier = 2
normalization = "BatchNorm"
